export const API_PATH = {
  AUTH_LOGIN: '/auth/login',
  AUTH_VERIFY_LOGIN_TWITTER: '/twitters/auth-url',
  BLOG: '/blogs',
  ORDER: '/order',
  ORDER_ID: (id: any) => `/order/${id}`,
  OFFER: '/offer',
  OFFER_ID: (id: any) => `/offer/${id}`,
  REPORT: '/report',
  ASSET: '/asset',
  ASSET_ID: (id: any) => `/asset/${id}`,
  CHANGE_STATUS_OFFER: (id: string) => `/offer/${id}/status`,
  SUBMIT_CODE_OFFER: (id: string) => `/offer/${id}/submit-code`,
  GET_INFO: '/user/profile',
  REGISTER_TELEGRAM: '/auth/register-telegram',
  OFFER_ONCHAIN: (id: string) => `/offer/${id}/submit-onchain`,
  FILL_OFFER: '/smart-contract/fill-offer',
  CHAT: '/chat',
  REPORT_CHAT: '/chat/report',
  BLOG_FOLLOWINGS: '/blogs/followings',
  BLOG_SAVED: '/blogs/saved',
  MODIFY_BLOG_SAVED: (id: string) => `/blogs/${id}/saved`,
  UPDATE_BLOG_VIEWS: (id: string) => `/blogs/${id}/views`,
  USER_PROFILE: '/user/profile',
  BLOGS_BEAR: (id: string) => `/blogs/${id}/bear`,
  BLOGS_BULL: (id: string) => `/blogs/${id}/bull`,
  ASSISTANT_CONVERSATION: '/assistant/conversation',
  THREAD: '/thread',
  MESSAGE: '/message',
  USER_UNSEEN: '/user/unseen-count',
  USER_SEEN: '/user/seen',
  REFRESH_PROFILE: '/user/refresh-profile',
};
